// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDuiXGFCZ-WpbNlsBRu7egkboJTG8QY4U',
    appId: '1:886131772827:web:70f8543d757d334f58253e',
    messagingSenderId: '886131772827',
    projectId: 'msb-companion',
    authDomain: 'msb-companion.firebaseapp.com',
    storageBucket: 'msb-companion.appspot.com',
    measurementId: 'G-QX01NPBYT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNwzv48yBJLnNcfsbzWBNhB91C8JR5E6o',
    appId: '1:886131772827:android:0d80c60533921a2358253e',
    messagingSenderId: '886131772827',
    projectId: 'msb-companion',
    storageBucket: 'msb-companion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkg5SoFAjUccK9oX8NdPVnjl2ghLiLQU8',
    appId: '1:886131772827:ios:9665e1776454b60d58253e',
    messagingSenderId: '886131772827',
    projectId: 'msb-companion',
    storageBucket: 'msb-companion.appspot.com',
    iosClientId: '886131772827-7mupp7dhvkm40102gsfq69khtcnas2gt.apps.googleusercontent.com',
    iosBundleId: 'com.mattmohandiss.msbcompanion',
  );
}
